config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :authors do
    resources :books
  end
  resources :people
  resources :logins
  resources :users

  # resource :basket, only: [:show, :update, :destroy]
 
  # resolve("Basket") { route_for(:basket) }

  # get '/patients/:id', to: 'patients#show'

  # get 'profile', action: :show, controller: 'users'

  # resource :geocoder
  # resolve('Geocoder') { [:geocoder] }

  # get '/patients/:id', to: 'patients#show', as: 'patient'
  # namespace :admin do
  #   resources :articles, :comments
  # end

  # scope module: 'admin' do
  #   resources :articles, :comments
  # end
  # resources :articles, module: 'admin'

  # scope '/admin' do
  #   resources :articles, :comments
  # end
  # resources :articles, path: '/admin/articles'
  # get '/posts' => 'posts#index'

  # resources :articles do
  #   resources :comments, shallow: true
  # end

  # resources :articles, shallow: true do
  #   resources :comments
  #   resources :quotes
  #   resources :drafts
  # end

  # resources :articles do
  #   resources :comments, only: [:index, :new, :create]
  # end
  # resources :comments, only: [:show, :edit, :update, :destroy]

  # concern :commentable do
  #   resources :comments
  # end   
  # concern :image_attachable do
  #   resources :images, only: :index
  # end
  # resources :messages, concerns: :commentable 
  # resources :articles, concerns: [:commentable, :image_attachable]
  # namespace :articles do
  #   concerns :commentable
  # end

  # resources :photos do
  #   member do
  #     get 'preview'
  #     # get 'a'
  #   end
  # end
  # resources :photos do
  #   get 'preview', on: :member
  # end

  # resources :photos do
  #   collection do
  #     get 'search'
  #   end
  # end
  # resources :comments do
  #   get 'preview', on: :new
  # end
  # get 'photos(/:id)', to: :display
  # get 'photos/:id/:user_id', to: 'photos#show'
  # get 'photos/:id/with_user/:user_id', to: 'photos#show'
  # get 'photos/:id', to: 'photos#show', defaults: { format: 'jpg' }
  # defaults format: :json do
  #   resources :photos
  # end

  # match 'photos', to: 'photos#show', via: [:get, :post]
  # match 'photos', to: 'photos#show', via: :all

  # get 'photos/:id', to: 'photos#show', constraints: { id: /[A-Z]\d{5}/ }
  # #get '/:id', to: 'articles#show', constraints: { id: /^\d/ }
  # get 'photos', to: 'photos#index', constraints: { subdomain: 'admin' }
  # get 'photos/*other/t', to: 'photos#unknownt'
  # get 'photos/*other', to: 'photos#unknown'
  # get '*a/foo/*b', to: 'photos#index'
  # get '*pages', to: 'photos#show', format: false
  # get '/stories', to: redirect('/articles')
  # get '/stories/:name', to: redirect('/articles/%{name}')
  # get '/stories/:name', to: redirect { |path_params, req| "/articles/#{path_params[:name].pluralize}" }
  # get '/stories', to: redirect { |path_params, req| "/articles/#{req.subdomain}" }

  # namespace :m do
  #   root to: "admin#index"
  # end
  direct :homepage do
    "http://www.rubyonrails.org"
  end
  direct :main do
    { controller: 'logins', action: 'new', subdomain: 'www' }
  end

  # resource :basket
  
  # resolve("Basket") { [:basket] }

  # resources :photos, path_names: { new: 'make', edit: 'change' }
  # resources :photos, as: 'images'
  # resources :user_permissions, controller: 'admin/user_permissions'

  # scope 'admin' do
  #   resources :photos, as: 'admin_photos'
  # end
   
  # resources :photos

  # scope 'admin', as: 'admin' do
  #   resources :photos, :accounts
  # end
   
  # resources :photos, :accounts

  # ActiveSupport::Inflector.inflections do |inflect|
  #   inflect.irregular 'tooth', 'teeth'
  # end

  # resources :people#, param: :identifier

end

app/models/author.rb
class Author < ApplicationRecord
  # has_many :books, dependent: :destroy
  has_many :books
  # has_many :books, dependent: :destroy, inverse_of: 'writer'
  # has_many :books do
  #   def find_by_book_prefix(id)
  #     find_by(id: id)
  #   end
  # end
  # accepts_nested_attributes_for :books
  accepts_nested_attributes_for :books, allow_destroy: true, 
    reject_if: lambda {|attributes| puts "attr: #{attributes}"; attributes.blank?}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  layout "max"
  Rails.application.config.session_store :cookie_store, key: '_your_app_session'
  def index
    @status = params[:status]
    @id = params[:ids]
  end

  def new
    # @author = Author.first
    # @book = @author.books.last
    # @book = @author.books.build
    @author = Author.last.books.create(published_at: Time.now).author
    # @author = Author.create(name: 'max').books.create(published_at: Time.now).author
    # @author = Author.new
    # 2.times { @author.books.build }
    render 'test'
  end

  def create
    @author = Author.new(author_params)
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    render 'test'
  end
 
  private
    def author_params
      params.require(:author).permit(:name, books_attributes: [:id, :author_id, :_destroy])
    end
  
end

app/views/authors/_author.html.erb
<h2><%= author.name %></h2>
 
<% if local_assigns[:full] %>
  <%= simple_format author.books_count %>
<% else %>

  <%= author.books_count %>
<% end %>

app/views/authors/index.html.erb
<%= @status %>
<%= @id %>

app/views/authors/test.html.erb
<% if false #start of comment %>
  <p><%= text_field(:author, :name) %></p>

  <%= form_for @author, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :books_count %>
    <%= f.submit "Create" %>
  <% end %>

  <%= form_for @author, url: {action: "create"} do |person_form| %>
    <%= person_form.text_field :name %>
    <%= fields_for @author.books do |contact_detail_form| %>
      <%= contact_detail_form.text_field :methods %>
    <% end %>
  <% end %>


  <% form_tag(author_path(@author), method: "patch") %>
  <%= select_tag(:city_id, options_for_select([['Lisbon', 1], ['Madrid', 2], ['indore', 3]], 3)) %>

  <%= select_tag(:city_id, options_for_select([
    ['Lisbon', 1, { 'data-size' => '2.8 million' }],
    ['Madrid', 2, { 'data-size' => '3.2 million' }],
    ['indore', 3, { 'data-size' => '2.5 million' }]
  ], 2)) %>
<% author_book_path(@book) %>

  <%= form_for @author,  html: {class: "nifty_form"} do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :books_count %>
    <%= f.submit "Create" %>
  <% end %>

  <%=form_for [@book.author, @book] do |f| %>
    <% f %>
  <% end %>

  <%= form_for @author do |f| %>
    <%= f.object.name %>
  <% end %>

  <%= form_for [@author, @book] do |f| %>
  <% end %>

  <%= form_for @author do |author| %>
    <%= author.text_field :name %>
    <% @author.books.each do |book| %>
      <%= author.fields_for book, index: book.id do |book_form|%>
        <%= book_form.text_field :author_id %>
      <% end %>
    <% end %>
  <% end %>

  <%= form_for @author do |author| %>
    <%= author.text_field :name %>
    <% @author.books.each do |book| %>
      <%= fields_for 'author[book]', book, index: book.id do |book_form| %>
        <%= book_form.text_field :author_id %>
      <% end %>
    <% end %>
  <% end %>

  <%= form_for @author do |f| %>
    Books:
    <ul>
      <%= f.fields_for :books do |books_form| %>
        <li>
          <%= books_form.label :id %>
          <%= books_form.text_field :id %>

          <%= books_form.label :author_id %>
          <%= books_form.text_field :author_id %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end #end of comment %>

  <%= form_for @author do |f| %>
    Author: <%= f.label f.object.name %> <br/>
    Books:
    <ul>
      <%= f.fields_for :books do |books_form| %>
        <li>
          <%= books_form.label :id %>
          <%= books_form.text_field :id %>

          <%= books_form.label :author_id %>
          <%= books_form.text_field :author_id %>

          <%= books_form.check_box :_destroy%>
        </li>
      <% end %>
    </ul>
    <%= f.submit %>
  <% end %>