config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :authors do
    resources :books
  end
  resources :people
  resources :logins
  resources :users

  # resource :basket, only: [:show, :update, :destroy]
 
  # resolve("Basket") { route_for(:basket) }

  # get '/patients/:id', to: 'patients#show'

  # get 'profile', action: :show, controller: 'users'

  # resource :geocoder
  # resolve('Geocoder') { [:geocoder] }

  # get '/patients/:id', to: 'patients#show', as: 'patient'
  # namespace :admin do
  #   resources :articles, :comments
  # end

  # scope module: 'admin' do
  #   resources :articles, :comments
  # end
  # resources :articles, module: 'admin'

  # scope '/admin' do
  #   resources :articles, :comments
  # end
  # resources :articles, path: '/admin/articles'
  # get '/posts' => 'posts#index'

  # resources :articles do
  #   resources :comments, shallow: true
  # end

  # resources :articles, shallow: true do
  #   resources :comments
  #   resources :quotes
  #   resources :drafts
  # end

  # resources :articles do
  #   resources :comments, only: [:index, :new, :create]
  # end
  # resources :comments, only: [:show, :edit, :update, :destroy]

  # concern :commentable do
  #   resources :comments
  # end   
  # concern :image_attachable do
  #   resources :images, only: :index
  # end
  # resources :messages, concerns: :commentable 
  # resources :articles, concerns: [:commentable, :image_attachable]
  # namespace :articles do
  #   concerns :commentable
  # end

  # resources :photos do
  #   member do
  #     get 'preview'
  #     # get 'a'
  #   end
  # end
  # resources :photos do
  #   get 'preview', on: :member
  # end

  # resources :photos do
  #   collection do
  #     get 'search'
  #   end
  # end
  # resources :comments do
  #   get 'preview', on: :new
  # end
  # get 'photos(/:id)', to: :display
  # get 'photos/:id/:user_id', to: 'photos#show'
  # get 'photos/:id/with_user/:user_id', to: 'photos#show'
  # get 'photos/:id', to: 'photos#show', defaults: { format: 'jpg' }
  # defaults format: :json do
  #   resources :photos
  # end

  # match 'photos', to: 'photos#show', via: [:get, :post]
  # match 'photos', to: 'photos#show', via: :all

  # get 'photos/:id', to: 'photos#show', constraints: { id: /[A-Z]\d{5}/ }
  # #get '/:id', to: 'articles#show', constraints: { id: /^\d/ }
  # get 'photos', to: 'photos#index', constraints: { subdomain: 'admin' }
  # get 'photos/*other/t', to: 'photos#unknownt'
  # get 'photos/*other', to: 'photos#unknown'
  # get '*a/foo/*b', to: 'photos#index'
  # get '*pages', to: 'photos#show', format: false
  # get '/stories', to: redirect('/articles')
  # get '/stories/:name', to: redirect('/articles/%{name}')
  # get '/stories/:name', to: redirect { |path_params, req| "/articles/#{path_params[:name].pluralize}" }
  # get '/stories', to: redirect { |path_params, req| "/articles/#{req.subdomain}" }

  # namespace :m do
  #   root to: "admin#index"
  # end
  direct :homepage do
    "http://www.rubyonrails.org"
  end
  direct :main do
    { controller: 'logins', action: 'new', subdomain: 'www' }
  end

  # resource :basket
  
  # resolve("Basket") { [:basket] }

  # resources :photos, path_names: { new: 'make', edit: 'change' }
  # resources :photos, as: 'images'
  # resources :user_permissions, controller: 'admin/user_permissions'

  # scope 'admin' do
  #   resources :photos, as: 'admin_photos'
  # end
   
  # resources :photos

  # scope 'admin', as: 'admin' do
  #   resources :photos, :accounts
  # end
   
  # resources :photos, :accounts

  # ActiveSupport::Inflector.inflections do |inflect|
  #   inflect.irregular 'tooth', 'teeth'
  # end

  # resources :people#, param: :identifier

end

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :writer, class_name: 'Author', foreign_key: 'author_id' 
  belongs_to :author
  # belongs_to :author, dependent: :destroy
  # belongs_to :author, counter_cache: true
  # belongs_to :author, autosave: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # protect_from_forgery except: :index
  layout "max"
  def index
    @books = Book.all
    @author = Author.first
    @authors = Author.all
    @kuchbhi = Author.first
    # render inline: "xml.p {'Horrid coding practice!'}", type: :builder
    # render inline: "<% @books.each do |p| %><p><%= p.author.books_count %></p><% end %>"
    # render html: helpers.tag.strong('Not Found')
    # render html: "<p>html</p>"
    # render json: @books
    # render xml: @books
    # render js: "alert('Hello Rails')";
    # render body: "<p>raw</p>"
    # render layout: "max"
    # photo = 'images/test.jpg'
    # render xml: photo, location: photo_url(photo)
    # render status: 500
    # render status: :forbidden    
    # render 'custom'
    # render 'show'
    render 'test'
  end

  def show
    @book = Book.find(params[:id])
    # puts(@book.published_at)
    # render html: helpers.tag.strong('Not Found')
    # photos_path = 'https://4.img-dpreview.com/files/p/E~TS590x0~articles/3925134721/0266554465.jpeg' 
    # redirect_to photos_path
    # redirect_to 'images/test.jpg'
    # redirect_back(fallback_location: root_path)
    # redirect_to photos_path, status: 301
    # render action: "index"
    # redirect_to action: :index
    # @books = Book.all
    # flash.now[:alert] = "Your book was not found"
    # render "index"
    # head :bad_request
    # head :forbidden
    # head :created, location: book_path(Book.first)

  end

  def update
    @book = Book.find(params[:id])
    if @book.touch()
      redirect_to(@book)
    else
      render "edit"
    end
  end

  def edit
    @author = Author.first
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% if false %>
  <p>book: <%= item.author_id %></p>
<% end %>

  <p>book: <%= book.author_id %></p>

app/views/books/_form.html.erb
<%= form_for(zone) do |f| %>
  <p>
    <b>Zone name</b><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/_link_area.html.erb
<p> this is link area</p>

app/views/books/_max.html.erb
<p><b>mayank is great</b></p>
    <% if false %>
        <%= javascript_include_tag "script" %> 
        <%= javascript_include_tag "script", "test_script_1" %> 
        <%= javascript_include_tag "test_script_1" %> 
        <%= stylesheet_link_tag "books" %> 
    <% end %>
<%= yield %>
<p><b>yes</b></p>

app/views/books/_search_filters.html.erb
<%= form_for(search) do |f| %>
  <h1>Search form:</h1>
  <fieldset>
    <%= yield f %>
  </fieldset>
  <p>
    <%= f.submit "Search" %>
  </p>
<% end %>

app/views/books/custom.html.erb
<% content_for :head do %>
  <title>Max</title>
<% end %>
 
<p>Hello, Mayank!</p>

app/views/books/edit.html.erb
<% if true %>
  <h1>New zone</h1>
  <%= render partial: "form", locals: {zone: @author} %>
<% end %>

app/views/books/index.html.erb
<h1>Listing Books</h1>
 
<table>
  <thead>
    <tr>
      <th>pub g</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.published_at %></td>
        <td><%= link_to "Show", book %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New book", new_book_path %>

<% content_for :content do %>  
  <%= render "search_filters", search: @books[0] do |f| %>
    <p>
      Name contains: <%= f.text_field :author_id_was %>
    </p>
  <% end %>
<% end %>

<% if false %>
  <h1>New zone</h1>
  <%= render partial: "form", locals: {zone: @author} %>

  <%= render @authors %>
  <%= render @author %>
  <%= render @kuchbhi %>
  
  <%= render partial: "authors/author", object: @new_author %>
  
  <h1>Authors</h1>
  <%= render partial: "authors/author", collection: @authors %>

  <h1>Contacts</h1>
  <%= render [@author, @authors[3], @books[0]] %>

  <%= render partial: "book", collection: @books, as: :item %>

  <%= render partial: @books, spacer_template: "link_area" %>

  <%= render partial: @books, layout: "max" %>
<% end %>

app/views/books/show.html.erb
<% if false %>
  <p>Show down</p>
  <%= render partial: "link_area", layout: "max" %>
<% end %>

<p><%= @book.author_id %></p>
<p><%= link_to "Edit", edit_book_path(@book) %></p>
<p><%= link_to "Destroy", @book, method: :delete, data: { confirm: "Are you sure?" } %></p>

app/views/books/test.html.erb
<% if false %>
  <p><%= text_field(:author, :name) %></p>
<% end %>

<%= form_for @author, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :books_count %>
  <%= f.submit "Create" %>
<% end %>